version: "3.8"
name: "alexandrina"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: alexandrina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/alexandrina
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SHOW_SQL: false
      FORMAT_SQL: false
      MAX_SIZE: 5GB
      PROFILES: deploy
      VIDEO_BUCKET: /app/videos/
      VIDEO_EXTENSION: .mp4
      VIDEO_PORTION: 5Mb
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - videos:/app/videos

volumes:
  database:
  videos: