spring:
  application:
    name: Alexandrina
  datasource:
    url: jdbc:postgresql://localhost:5432/alexandrina
    username: postgres
    password: Egor2004
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB